import { StoreProvider } from "@/store/StoreProvider";
import { Geist, Geist_Mono } from "next/font/google";
import 'simplebar-react/dist/simplebar.min.css';
import 'react-toastify/dist/ReactToastify.css';
import "flatpickr/dist/themes/light.css";
import "react-svg-map/lib/index.css";
import '@/assets/scss/app.css';
import "./globals.css";
import  ToastProvider  from "@/components/toastify/ToastifyClient";
// import { ToastContainer, toast } from 'react-toastify';

import localFont from 'next/font/local'

// this way for local font for optmize when page load not takes alot time to get fonts
const PlusJakartaSans = localFont({
  src: '../../public/fonts/PlusJakartaSans-Medium.ttf',
  weight: '400',
  style: 'normal',
  display: 'swap',
  variable: '--font-PlusJakartaSans', 
})
export const metadata = {
  title: "MED Intell Medical project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en" dir="ltr">
      <body
        className={`${PlusJakartaSans.variable} antialiased`}
      >

      

        <StoreProvider>
          {children}
        </StoreProvider>
         <ToastProvider/> 
        {/* </ToastProvider > */}

      </body>
    </html>
  );
}
